version: 2

builds:
  - dir: ./target
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - formats: ["binary"]
    name_template: "{{ .Os }}-{{ .Arch }}"

release:
  github:
    owner: quad
    name: gh-stack-jj
