version: 2

before:
  hooks:
    - mise build

builds:
  - dir: ./target
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64

release:
  github:
    owner: quad
    name: gh-stack-jj
