[tools]
goreleaser = "2.17.1"
lisette = "0.11.2"

[tasks.build]
description = "Format, check, test, and build"
run = [
  "lis format",
  "lis check",
  "lis test",
  "lis build",
]

[tasks.release]
description = "Release to Github"
run = "goreleaser release"
